// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjf6Qw1_nTn3WL_rmV3s64j3aoeCTSSFE',
    appId: '1:103889858891:web:d33f2fe244705ff11638ce',
    messagingSenderId: '103889858891',
    projectId: 'chat-app-6e1af',
    authDomain: 'chat-app-6e1af.firebaseapp.com',
    storageBucket: 'chat-app-6e1af.appspot.com',
    measurementId: 'G-SJJS93MKS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5D_bWV2ZxVULV9pCfZqKxy2Msye9MN_0',
    appId: '1:103889858891:android:c2c64196b2ed9e661638ce',
    messagingSenderId: '103889858891',
    projectId: 'chat-app-6e1af',
    storageBucket: 'chat-app-6e1af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20NmoUOq9z-2LIpGiUCeUBuGq0yUjk8M',
    appId: '1:103889858891:ios:bbbaf52ffbcb34f61638ce',
    messagingSenderId: '103889858891',
    projectId: 'chat-app-6e1af',
    storageBucket: 'chat-app-6e1af.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD20NmoUOq9z-2LIpGiUCeUBuGq0yUjk8M',
    appId: '1:103889858891:ios:94f992e1fc5f93581638ce',
    messagingSenderId: '103889858891',
    projectId: 'chat-app-6e1af',
    storageBucket: 'chat-app-6e1af.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
